### ISSUE TITLE
Experiment with Hugo to generate site

### ISSUE THREAD

**Issue by rgreinho** [scrapd/docs#5]
Issue Type
----------

- Feature request

Current Behavior
----------------

We are currently using [MkDocs](https://www.mkdocs.org/) with the [Material theme](https://squidfunk.github.io/mkdocs-material/). 

Expected Behavior
-----------------

While MkDocs works very well and we have a fully automated pipeline around it, the number of available themes is very limited. Besides they all look too technical-documentation oriented. 

As a maintainer I would like to provide a site which could act as a landing page and a documentation site. Ideally we should be able to post articles as well, like a blog (for announcements for instance).

Possible Solution
-----------------

[Hugo](https://gohugo.io/) is great for this task and has very good themes. The [Syna theme](https://themes.gohugo.io/syna) seems to match all the criteria.

**Comment by stp-ip** [comment]
Hey happy to see the interest in using Syna. Wanted to check in and see, how it is working out and what general feedback is available and anything I could help with in the transition (when still on the table).

**Comment by rgreinho** [comment]
Hi @stp-ip! Syna looks very nice and has the features we were looking for. 

However we stopped investigating switching documentation generator because Hugo + Syna is more involved (fragments, etc.) than simply putting markdown files in a folder like we do with MkDocs. 

But I'll definitely be in touch if we reopen this issue!

**Comment by stp-ip** [comment]
Thanks for the feedback. Yeah we do our best to be simple, but flexible, which ends up being a bit more involved than feels perfect. We'll definitely work on simplifying use cases and default more things so it works out of the box more often.
